### ISSUE TITLE
429 on login

### ISSUE THREAD

**Issue by adyanth** [bernd-wechner/Degoo#31]
I was trying to use this tool to backup my NAS to Degoo. Started with cloning this repo to python:3-alpine, installed libmagic and all the requirements.

When trying to login using `python commands.py login`, I get a 429 like so:
```bash
/usr/src/Degoo # python commands.py login
username: <emailID>
Password:
Login failed with: 429: Too Many Requests
Login failed.
/usr/src/Degoo #
```

Am I doing something wrong here?

**Comment by adyanth** [comment]
Looks like the login API is at https://degoo.com/me/login and the POST request takes `application/x-www-form-urlencoded` rather than JSON with CSRF.

**Comment by bernd-wechner** [comment]
Are you using the latest code base (pulled from here)? We just fixed a 429 issue yesterday as it happens. I see this now:

```
$ ./degoo_login -fvvv
Request:
	URL: https://rest-api.degoo.com/login
	method: POST
	headers:
		User-Agent: Degoo-client/0.3
		Accept: */*
		Accept-Language: en-US,en;q=0.5
		Accept-Encoding: gzip, deflate
		Content-Type: application/json
		Origin: https://app.degoo.com
		Content-Length: 61
	body:
		{"Username":"<redacted>","Password":"<redacted>"}
Response:
	status: 200
	reason: OK
	headers:
		Date: Mon, 26 Jul 2021 09:01:22 GMT
		Content-Type: application/json
		Transfer-Encoding: chunked
		Connection: keep-alive
		CF-Ray: 674c71612fd017cf-MEL
		Access-Control-Allow-Origin: *
		Via: 1.1 7799fcaed3aefe6ff8b2d01a9d1fddcd.cloudfront.net (CloudFront)
		CF-Cache-Status: DYNAMIC
		Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
		x-amz-apigw-id: DEf7WFljoAMFg_w=
		X-Amz-Cf-Id: sUYjpCnlsA9CVWAydCFwSIRfqBnCB7u0-eE-yhkBQPx14dJfZDdaVg==
		X-Amz-Cf-Pop: ATL51-C1
		x-amzn-RequestId: 3369654a-13ea-43b0-95ef-bc2b86dd9fd5
		X-Amzn-Trace-Id: Root=1-60fe79e2-3bea0647717211800fec05fc;Sampled=0
		X-Cache: Miss from cloudfront
		Vary: Accept-Encoding
		Server: cloudflare
		Content-Encoding: gzip
	content:
		b'  {"Token":"<redacted>","RefreshToken":"","Redirect":"/moments"}\n'
Successfully logged in.
```
Try the latest code base, and if still no luck post the results of a login effort with `-vvv ` redacting out your personal details. I may add a redacting option tonight to make that easier.

**Comment by bernd-wechner** [comment]
Well, it was a trivial add so while waiting for dinner, I added redacting. Now try: `degoo_login -rvvv`

Note that if you succeed in logging in your credentials are written to file and you can subsequently login with the `-f` option to draw them from file. Up to you to keep the credentials file secure. It is stored in:

    conf_dir = user_config_dir("degoo")
    cred_file = os.path.join(conf_dir, "credentials.json")

To find out where that is on your system I added quickly the `degoo_config` command, which will report it. Make sure the credentials and key files are secure. They record the access details to your account.

**Comment by adyah-cisco** [comment]
This is what it shows with -rvvvv

```
Request:
        URL: https://rest-api.degoo.com/login
        method: POST
        headers:
                User-Agent: Degoo-client/0.3
                Accept: */*
                Accept-Language: en-US,en;q=0.5
                Accept-Encoding: gzip, deflate
                Content-Type: application/json
                Origin: https://app.degoo.com
                Content-Length: 55
        body:
                {"Username":"<redacted>","Password":"<redacted>"}
Response:
        status: 429
        reason: Too Many Requests
        headers:
                Date: Mon, 26 Jul 2021 09:53:07 GMT
                Content-Type: text/plain;charset=UTF-8
                Content-Length: 0
                Connection: keep-alive
                Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                Vary: Accept-Encoding
                Server: cloudflare
                CF-RAY: 674cbd342bca1d3f-MAA
        content:
                b''
Login failed with: 429: Too Many Requests
Login failed.
```

**Comment by bernd-wechner** [comment]
Interesting. I was seeing this myself on the weekend. And I removed the keep-alive request from the request headers and it went away. Reported here:

https://github.com/bernd-wechner/Degoo/issues/25#issuecomment-886154851

As I'm not seeing the error now I can't experiment on it. Trying to understand it theoretically has yielded no fruit.

You see the 429 is reported by cloudflare, which is accompanied by a series of worthy observations:

1. cloudflare is a very popular CDN (content delivery network) and  I use it myself a lot. They provide otehr services too which I'm not familiar with off hand.
2. I see zero reason for the login command to be drawing nay content from cloudflare, no login on any server typically, woud I expect to be leaning on a third party. But who knows.
3. Examining the full body of loaded code on both the login page and the moments page (to which it redirects reveals zero references to cloudflare. 
4. Logging in on the wbe page the login request is submitted by Firefox with these headers:
```
POST /login HTTP/1.1
Host: rest-api.degoo.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 82
Origin: https://app.degoo.com
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
DNT: 1
Sec-GPC: 1
Connection: keep-alive
```
That last one is the one I removed to get it working here yesterday. Using it I found the 429 error reported.  What you can do is capture your web login headers similarly or use these and here:

https://github.com/bernd-wechner/Degoo/blob/28ec3eb2f279a1927a84f123e8ec7de1a22b3c7c/degoo/API.py#L307

you can try to mimic those headers step by step to see if you find a combination that works. Their API seems very fiddly in this space. And we are reverse engineering it with a black box approach alas (we have no access to their code). So it needs someone like yourself who can reproduce a given problem to perform these experiments,. Technically if you use those exact headers the login should/must succeed (it works for Firefox).

The body Firefox submitted is as follows:
```
{"Username":"<redacted>","Password":"<redacted>","GenerateToken":true}
```
Which is clearly different to ours, it seems they have added a field since I last inspected. This is another problem we have, a moving target. 

I will quickly adapt with news findings and test and push.

**Comment by bernd-wechner** [comment]
OK so I quickly added the GenerateToken request and placed that Firefox set of headers as comment in the code. I added all the remaining ones and lo and behold if I add just a single one of the Sec or DNT or Connection headers I get a 429 error. Leave them off and I can log in. I have pushed the code with which I can log in. 

If you want to capture your headers in your browser and post them, please do.

If you don't know how, it's outlined in the README. But basically surf to the login page, press F12, click the network tab, clear it if it's full, login and the first entry is generally the login request. Inspect that, and get the raw headers and body.

**Comment by adyah-cisco** [comment]
Sure thing @bernd-wechner I can test all these out gladly. 

Regarding Cloudflare, they have this [Argo Tunnel](https://www.cloudflare.com/products/tunnel/) which protects the origin by having a tunnel from the hosting server to cloudflare, rather than exposing the server directly. I use this myself to host a bunch of services in my homelab. All requests would be reverse proxied by Cloudflare no matter what.

When I logged in by myself on the UI, I saw it send `application/x-www-form-urlencoded` with my username and password and the endpoint was not rest-api.degoo.com. I'm thinking if maybe this is geographically dependent?

I'll send the headers and everything soon.

**Comment by adyah-cisco** [comment]
Okay, checking now, it is JSON. Let me test again with the latest changes you made!

```
headers = {
    'sec-ch-ua': '" Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"',
    'Referer': '',
    'sec-ch-ua-mobile': '?0',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 Edg/91.0.864.71',
    'Content-Type': 'application/json',
}

data = '{"Username":"<redacted>","Password":"<redacted>","GenerateToken":true}'

response = requests.post('https://rest-api.degoo.com/login', headers=headers, data=data)
```

**Comment by adyah-cisco** [comment]
Even after adding the Generate token to the code, I see the 429.

```
Request:
        URL: https://rest-api.degoo.com/login
        method: POST
        headers:
                User-Agent: Degoo-client/0.3
                Accept: */*
                Accept-Language: en-US,en;q=0.5
                Accept-Encoding: gzip, deflate
                Content-Type: application/json
                Origin: https://app.degoo.com
                Content-Length: 66
        body:
                {"Username":"<redacted>","Password":"<redacted>","GenerateToken":true}
Response:
        status: 429
        reason: Too Many Requests
        headers:
                Date: Mon, 26 Jul 2021 11:38:51 GMT
                Content-Type: text/plain;charset=UTF-8
                Content-Length: 0
                Connection: keep-alive
                Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                Vary: Accept-Encoding
                Server: cloudflare
                CF-RAY: 674d5817bc581d3d-BLR
        content:
                b''
Login failed with: 429: Too Many Requests
Login failed.
```

**Comment by adyah-cisco** [comment]
But sometimes I see this happening on login:

```
cookies = {
    'lang': '',
    'pid': '',
    '__RequestVerificationToken': 'UktVeqbk8CP-zEPzsHNOwMK2YxXVS2uJ-XrHKp4Pt_1YAiKkPJ-lTY7f6b5rSolCNniPzOO-e9aDmThv_pkVLpBnVp1_3wI0-DUUuz1ysqE1',
    'invite': '',
    'AcceptCookies': '',
    '__stripe_mid': '22b9b296-9cba-49ef-a396-d161290d47d0be71be',
    '__stripe_sid': 'a16e2100-7aec-4de6-9a7d-f51e77e4ac690bbda0',
}

headers = {
    'authority': 'degoo.com',
    'cache-control': 'max-age=0',
    'sec-ch-ua': '" Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"',
    'sec-ch-ua-mobile': '?0',
    'upgrade-insecure-requests': '1',
    'origin': 'https://degoo.com',
    'content-type': 'application/x-www-form-urlencoded',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 Edg/91.0.864.71',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-user': '?1',
    'sec-fetch-dest': 'document',
    'referer': 'https://degoo.com/',
    'accept-language': 'en-US,en;q=0.9',
}

data = {
  '__RequestVerificationToken': 'CIip6F_dW94k9FZJf66cApY3sB-U44e_8Wz2Fk-gWAQojmu4wY3DQ2VR223jfSFx-FJeCdeBxHxbonuiRVO0QpMmZtRHkgkHwlvFcOH38MI1',
  'returnUrl': '',
  'source': '',
  'premiumID': '',
  'Email': '<redacted>',
  'Password': '<redacted>'
}

response = requests.post('https://degoo.com/me/login', headers=headers, cookies=cookies, data=data)
```

**Comment by adyah-cisco** [comment]
The different requests happen depending on if I login to https://app.degoo.com/login or https://degoo.com/me/login

So, seems like two different endpoints for now. Still checking why am I getting 429.

Tried with all the headers added by the browser (Edge), still no luck.

```
Request:
        URL: https://rest-api.degoo.com/login
        method: POST
        headers:
                User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 Edg/91.0.864.71
                Accept-Language: en-US,en;q=0.9
                Accept-Encoding: gzip, deflate, br
                Content-Type: application/json
                Referer: 
                sec-ch-ua: " Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"
                sec-ch-ua-mobile: ?0
                sec-fetch-site: same-site
                sec-fetch-mode: cors
                sec-fetch-dest: empty
                Origin: https://app.degoo.com
                Content-Length: 76
        body:
                {"Username":"<redacted>","Password":"<redacted>","GenerateToken":true}
Response:
        status: 429
        reason: Too Many Requests
        headers:
                Date: Mon, 26 Jul 2021 12:00:42 GMT
                Content-Type: text/plain;charset=UTF-8
                Content-Length: 0
                Connection: keep-alive
                Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                Vary: Accept-Encoding
                Server: cloudflare
                CF-RAY: 674d781bbb051d18-BLR
        content:
                b''
Login failed with: 429: Too Many Requests
Login failed.
```
